runtime: java
env: flex
service: wallet-landing
#instance_class: F1

#automatic_scaling:
#  min_idle_instances: 0
#  max_idle_instances: 1  # default value
#  min_pending_latency: 30ms  # default value
#  max_pending_latency: automatic
#  max_concurrent_requests: 50
  
#resources:
#  cpu: 1
#  memory_gb: 0.1
#  disk_size_gb: 10